import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import contactsRouter from "./contacts";
import companiesRouter from "./companies";
import tasksRouter from "./tasks";
import dashboardRouter from "./dashboard";
import searchRouter from "./search";
import exportRouter from "./export";
import treatmentPlansRouter from "./treatment-plans";
import financialRouter from "./financial";
import notificationsRouter from "./notifications";
import patientPortalRouter from "./patient-portal";
import attachmentsRouter from "./attachments";
import clinicalRecordsRouter from "./clinical-records";
import quotesRouter from "./quotes";
import inventoryRouter from "./inventory";
import commissionsRouter from "./commissions";

const router: IRouter = Router();

router.use(patientPortalRouter);
router.use(healthRouter);
router.use(authRouter);
router.use(searchRouter);
router.use(exportRouter);
router.use(contactsRouter);
router.use(companiesRouter);
router.use(tasksRouter);
router.use(dashboardRouter);
router.use(treatmentPlansRouter);
router.use(financialRouter);
router.use(notificationsRouter);
router.use("/attachments", attachmentsRouter);
router.use("/clinical-records", clinicalRecordsRouter);
router.use("/quotes", quotesRouter);
router.use(inventoryRouter);
router.use(commissionsRouter);

export default router;
